language: c
compiler: gcc
sudo: required
addons: 
  apt: 
    packages: 
      - libpcap-dev

install:
  - cd $HOME 
  - curl -o sdk.bz2 https://downloads.openwrt.org/snapshots/trunk/ar71xx/generic/OpenWrt-SDK-ar71xx-generic_gcc-4.8-linaro_musl-1.1.11.Linux-x86_64.tar.bz2
  - tar xfj sdk.bz2 
  - mkdir sdk/package/port-mirroring/ 
  - cp openwrt/Makefile sdk/package/port-mirroring/ 

script: 
  - autoreconf -vfi && ./configure && make && make cppcheck
  - cd sdk && make package/port-mirroring/compile 
