language: c
compiler: gcc
sudo: false
addons: 
  apt: 
    packages: 
      - libpcap-dev

install:
  - wget https://downloads.openwrt.org/snapshots/trunk/ar71xx/generic/OpenWrt-SDK-ar71xx-generic_gcc-4.8-linaro_musl-1.1.11.Linux-x86_64.tar.bz2
  - tar xfj *bz2 
  - mv OpenWrt-SDK-* openwrt-sdk
  - mkdir openwrt-sdk/package/port-mirroring 
  - cp openwrt/Makefile openwrt-sdk/package/port-mirroring 

script: 
  - autoreconf -vfi && ./configure && make && make cppcheck
  - cd openwrt-sdk && make package/port-mirroring/compile 
